const campaigns = [
  {
    name: "Run for Cancer Research",
    description: "A 120K charity run to raise money for cancer research.",
    city: "New York",
    address: "Central Park",
    startDate: new Date("2023-05-15T08:00:00Z"),
    endDate: new Date("2023-05-15T11:00:00Z"),
    image: "https://example.com/run-for-cancer-research.jpg",
    goal: 120000,
    organizer: "Cancer Research Foundation",
    contactEmail: "info@cancerresearchfoundation.org",
    contactPhone: "555-555-5555",
  },
  {
    name: "Community Food Drive",
    description:
      "A food drive to collect non-perishable food items for a local food bank.",
    city: "Chicago",
    address: "Main Street",
    startDate: new Date("2023-04-15T10:00:00Z"),
    endDate: new Date("2023-04-15T14:00:00Z"),
    image: "https://example.com/community-food-drive.jpg",
    goal: 2000,
    organizer: "Community Volunteers",
    contactEmail: "info@communityvolunteers.org",
    contactPhone: "555-555-5555",
  },
  {
    name: "Virtual Auction for Education",
    description:
      "A virtual auction featuring unique items to support education for underprivileged children.",
    city: "New York",
    address: "123 Main Street",
    startDate: new Date("2023-07-01T08:00:00Z"),
    endDate: new Date("2023-07-15T17:00:00Z"),
    image: "https://example.com/virtual-auction-for-education.jpg",
    goal: 15000,
    organizer: "Education for All Foundation",
    contactEmail: "info@educationforallfoundation.org",
    contactPhone: "555-555-5555",
  },

  {
    name: "Hope Gala Dinner",
    description:
      "A gala dinner to raise money for a homeless shelter and support homeless individuals.",
    city: "San Francisco",
    address: "Fairmont Hotel",
    startDate: new Date("2023-09-30T18:00:00Z"),
    endDate: new Date("2023-09-30T22:00:00Z"),
    image: "https://example.com/hope-gala-dinner.jpg",
    goal: 25000,
    organizer: "Hope for the Homeless",
    contactEmail: "info@hopeforthehomeless.org",
    contactPhone: "555-555-5555",
  },
  {
    name: "Clean Energy for a Better Future",
    description:
      "A fundraising campaign to support clean energy initiatives and combat climate change.",
    city: "San Francisco",
    address: "456 Elm Street",
    startDate: new Date("2023-05-01T09:00:00Z"),
    endDate: new Date("2023-06-30T17:00:00Z"),
    image: "https://example.com/clean-energy-for-a-better-future.jpg",
    goal: 25000,
    organizer: "Green Energy Foundation",
    contactEmail: "info@greenenergyfoundation.org",
    contactPhone: "555-555-5555",
  },
  {
    name: "Saving Lives through Medical Research",
    description:
      "A fundraising campaign to support medical research and find cures for life-threatening diseases.",
    city: "Boston",
    address: "789 Oak Street",
    startDate: new Date("2023-08-01T08:00:00Z"),
    endDate: new Date("2023-09-30T17:00:00Z"),
    image: "https://example.com/saving-lives-through-medical-research.jpg",
    goal: 50000,
    organizer: "Medical Research Foundation",
    contactEmail: "info@medicalresearchfoundation.org",
    contactPhone: "555-555-5555",
  },
  {
    name: "Empowering Women through Education",
    description:
      "A fundraising campaign to provide education and vocational training to women in underprivileged communities.",
    city: "Chicago",
    address: "101 Maple Avenue",
    startDate: new Date("2023-03-01T09:00:00Z"),
    endDate: new Date("2023-04-30T17:00:00Z"),
    image: "https://example.com/empowering-women-through-education.jpg",
    goal: 100000,
    organizer: "Women's Education Foundation",
    contactEmail: "info@womenseducationfoundation.org",
    contactPhone: "555-555-5555",
  },
  {
    name: "Save the Rainforest",
    description: "A fundraising campaign to support rainforest conservation efforts.",
    city: "Rio de Janeiro",
    address: "Ipanema Beach",
    startDate: "2023-08-01T08:00:00Z",
    endDate: "2023-08-31T08:00:00Z",
    image: "https://example.com/save-the-rainforest.jpg",
    goal: 350000,
    organizer: "Rainforest Alliance",
    contactEmail: "info@rainforestalliance.org",
    contactPhone: "+1-800-248-8222"
},
{
  name: "Help Feed the Hungry",
  description: "A food drive to support the local food bank.",
  city: "Chicago",
  address: "Downtown",
  startDate: "2023-04-15T08:00:00Z",
  endDate: "2023-04-30T08:00:00Z",
  image: "https://example.com/help-feed-the-hungry.jpg",
  goal: 45000,
  organizer: "Greater Chicago Food Depository",
  contactEmail: "info@gcfd.org",
  contactPhone: "312-644-3663"
}


];
module.exports = campaigns;